import {
  loadPrototypeDb,
  persistPrototypeDb,
  PrototypeDatabase,
  StoredPartner,
  StoredPartnerUser,
} from '@/lib/storage/prototype-db'

const PROTOTYPE_SEED_VERSION = 21

const buildSeedPartners = (): StoredPartner[] => [
  {
    id: 'partner-save-the-children',
    organizationName: 'Save the Children International',
    organizationType: 'ngo',
    logo: '/partners/save-the-children.svg',
    description: 'Global NGO focused on ensuring every child has the future they deserve.',
    mission: 'Create sustainable, child-centered programs that improve education and wellbeing worldwide.',
    website: 'https://www.savethechildren.net',
    contactEmail: 'partnerships@savethechildren.org',
    contactPhone: '+45 33 73 20 00',
    country: 'DK',
    languages: ['en', 'da'],
    sdgFocus: ['SDG 4', 'SDG 5', 'SDG 10'],
    createdAt: '2025-01-10T09:00:00.000Z',
    updatedAt: '2025-03-01T10:15:00.000Z',
    isActive: true,
    verificationStatus: 'verified',
  },
  {
    id: 'partner-lego-foundation',
    organizationName: 'LEGO Foundation',
    organizationType: 'commercial',
    logo: '/partners/lego-foundation.svg',
    description: 'Philanthropic arm of LEGO Group supporting learning through play.',
    mission: 'Inspire and develop the builders of tomorrow through playful learning experiences.',
    website: 'https://www.legofoundation.com',
    contactEmail: 'partnerships@legofoundation.com',
    contactPhone: '+45 79 50 60 70',
    country: 'DK',
    languages: ['en', 'da'],
    sdgFocus: ['SDG 4', 'SDG 9'],
    createdAt: '2025-01-14T11:30:00.000Z',
    updatedAt: '2025-02-20T13:45:00.000Z',
    isActive: true,
    verificationStatus: 'verified',
  },
  {
    id: 'partner-unicef',
    organizationName: 'UNICEF Denmark',
    organizationType: 'ngo',
    logo: '/partners/unicef.svg',
    description: 'UN agency delivering development programs with a focus on education equity.',
    mission: 'Advance children’s rights and equitable access to transformative learning programmes.',
    website: 'https://www.unicef.org',
    contactEmail: 'learninglab@unicef.org',
    contactPhone: '+41 22 909 50 11',
    country: 'DK',
    languages: ['en', 'da'],
    sdgFocus: ['SDG 4', 'SDG 16', 'SDG 17'],
    createdAt: '2025-01-18T08:45:00.000Z',
    updatedAt: '2025-02-25T09:20:00.000Z',
    isActive: true,
    verificationStatus: 'verified',
  },
  {
    id: 'partner-unicef-england',
    organizationName: 'UNICEF England',
    organizationType: 'ngo',
    logo: '/partners/unicef.svg',
    description: 'UNICEF UK country team coordinating education partnerships and climate action labs.',
    mission: 'Equip young people in the UK and partner countries to collaborate on global challenges.',
    website: 'https://www.unicef.org.uk',
    contactEmail: 'education@unicef.org.uk',
    contactPhone: '+44 20 0000 1111',
    country: 'UK',
    languages: ['en'],
    sdgFocus: ['SDG 4', 'SDG 13', 'SDG 17'],
    createdAt: '2025-02-01T08:45:00.000Z',
    updatedAt: '2025-03-15T09:20:00.000Z',
    isActive: true,
    verificationStatus: 'verified',
  },
  {
    id: 'partner-alm-brand',
    organizationName: 'Alm. Brand Foundation',
    organizationType: 'foundation',
    logo: '/partners/alm-brand.svg',
    description: 'Danish sponsor supporting community wellbeing and resilience initiatives in schools.',
    mission: 'Invest in programmes that strengthen communities and empower young people to thrive together.',
    website: 'https://www.almbrand.dk',
    contactEmail: 'partnerships@almbrand.dk',
    contactPhone: '+45 35 47 47 47',
    country: 'DK',
    languages: ['da', 'en'],
    sdgFocus: ['SDG 3', 'SDG 11'],
    createdAt: '2025-01-12T08:30:00.000Z',
    updatedAt: '2025-03-02T09:45:00.000Z',
    isActive: true,
    verificationStatus: 'verified',
  },
]

const buildSeedPartnerUsers = (): StoredPartnerUser[] => [
  {
    id: 'partner-user-stc-director',
    partnerId: 'partner-save-the-children',
    email: 'director@savethechildren.org',
    firstName: 'Amara',
    lastName: 'Jensen',
    role: 'admin',
    hasAcceptedTerms: true,
    twoFactorEnabled: true,
    createdAt: '2025-01-10T09:05:00.000Z',
    lastLoginAt: '2025-03-03T07:55:00.000Z',
    isActive: true,
  },
  {
    id: 'partner-user-lego-lead',
    partnerId: 'partner-save-the-children',
    email: 'partnerships@legofoundation.com',
    firstName: 'Luca',
    lastName: 'Villadsen',
    role: 'collaborator',
    hasAcceptedTerms: true,
    twoFactorEnabled: false,
    createdAt: '2025-01-14T11:32:00.000Z',
    lastLoginAt: '2025-02-28T12:05:00.000Z',
    isActive: true,
  },
  {
    id: 'partner-user-unicef-coordination',
    partnerId: 'partner-unicef',
    email: 'coordinator@unicef.org',
    firstName: 'Naila',
    lastName: 'Rahman',
    role: 'collaborator',
    hasAcceptedTerms: true,
    twoFactorEnabled: true,
    createdAt: '2025-01-18T08:50:00.000Z',
    lastLoginAt: '2025-03-02T09:30:00.000Z',
    isActive: true,
  },
  {
    id: 'partner-user-almbrand-sponsor',
    partnerId: 'partner-alm-brand',
    email: 'community@almbrand.dk',
    firstName: 'Mette',
    lastName: 'Hansen',
    role: 'collaborator',
    hasAcceptedTerms: true,
    twoFactorEnabled: false,
    createdAt: '2025-01-19T09:10:00.000Z',
    lastLoginAt: '2025-02-28T14:20:00.000Z',
    isActive: true,
  },
]

const buildSeedPrograms = (): PrototypeDatabase['programs'] => [
  {
    id: 'program-build-the-change-2025',
    partnerId: 'partner-lego-foundation',
    displayTitle: 'Save the Children x LEGO: Build the Change',
    name: 'Build the Change',
    marketingTagline: 'Playful design labs where children imagine sustainable futures with LEGO bricks.',
    description:
      'Build the Change empowers children, primarily aged 6–13, to imagine and build solutions for a better, more sustainable future. Through creative workshops using LEGO bricks, children explore real-world environmental challenges and express their ideas for change. The programme is rooted in Learning through Play, fostering engagement, critical thinking, collaboration, and creative problem-solving. This playful, hands-on approach links learning to real-life experiences, giving children a voice while developing key cognitive and emotional skills.',
    projectTypes: ['cultural_exchange', 'explore_global_challenges', 'create_solutions'],
    pedagogicalFramework: ['steam', 'pbl', 'design_thinking'],
    learningGoals:
      'Nurture creativity and agency by guiding children to prototype sustainable solutions, document their thinking, and present stories of impact to their communities.',
    targetAgeRanges: ['6-8', '9-11', '12-14'],
    countriesInScope: ['DK', 'IT', 'MX', 'BR'],
    sdgFocus: [4, 11, 13],
    crcFocus: ['28', '31'],
    supportingPartnerId: 'partner-lego-foundation',
    supportingPartnerRole: 'co_host',
    startDate: '2025-01-10',
    endDate: '2025-12-20',
    programUrl: 'https://prototype.class2class.org/programs/build-the-change',
    brandColor: '#F0B90B',
    logo: '/programs/build-the-change/logo.svg',
    heroImageUrl: '/images/build-the-change.png',
    status: 'active',
    isPublic: true,
    createdAt: '2025-01-05T08:00:00.000Z',
    updatedAt: '2025-03-05T12:10:00.000Z',
    createdBy: 'partner-user-stc-director',
  },
  {
    id: 'program-communities-2025',
    partnerId: 'partner-unicef',
    displayTitle: 'UNICEF Denmark: Communities in Focus',
    name: 'UNICEF Denmark: Communities in Focus',
    marketingTagline: 'Design-thinking projects that strengthen school communities across borders.',
    description:
      'Each class works, within the Communities theme, to investigate a local case or challenge that affects their students’ well-being or sense of community at school. Students conduct surveys, gather stories, and share findings with partner classrooms before prototyping actions that build stronger communities.',
    projectTypes: ['cultural_exchange', 'explore_global_challenges', 'create_solutions'],
    pedagogicalFramework: ['design_thinking', 'pbl', 'global_citizenship'],
    learningGoals:
      'Guide students through an empathy-driven, iterative design process where they define community challenges, co-create solutions, and act on their findings with partner schools.',
    targetAgeRanges: ['12-14', '15-18'],
    countriesInScope: ['DK'],
    sdgFocus: [3, 4, 11],
    crcFocus: ['12', '24', '31'],
    supportingPartnerId: 'partner-alm-brand',
    supportingPartnerRole: 'sponsor',
    startDate: '2025-02-01',
    endDate: '2025-12-10',
    programUrl: 'https://prototype.class2class.org/programs/communities-in-focus',
    brandColor: '#5B8DEF',
    logo: '/programs/communities-in-focus/logo.svg',
    heroImageUrl: '/images/unicef-community.png',
    status: 'active',
    isPublic: true,
    createdAt: '2025-01-20T09:00:00.000Z',
    updatedAt: '2025-03-06T11:15:00.000Z',
    createdBy: 'partner-user-unicef-coordination',
  },
  {
    id: 'program-child-world-2025',
    partnerId: 'partner-unicef',
    displayTitle: 'Child in the World',
    name: 'Child in the World',
    marketingTagline: 'UK-DK classrooms co-create projects on children’s rights and community.',
    description:
      'British and Danish classes pair up to explore children’s rights, well-being, and community belonging. Students exchange stories, co-design small actions, and present joint showcases.',
    projectTypes: ['cultural_exchange', 'explore_global_challenges', 'create_solutions'],
    pedagogicalFramework: ['pbl', 'global_citizenship', 'design_thinking'],
    learningGoals:
      'Help learners compare lived experiences, practice empathy, and prototype shared actions that strengthen student voice across borders.',
    targetAgeRanges: ['12-14', '15-18'],
    countriesInScope: ['DK', 'UK'],
    sdgFocus: [4, 10, 16],
    crcFocus: ['12', '13', '31'],
    supportingPartnerId: 'partner-unicef-england',
    supportingPartnerRole: 'co_host',
    startDate: '2025-03-15',
    endDate: '2025-12-20',
    programUrl: 'https://prototype.class2class.org/programs/child-in-the-world',
    brandColor: '#4F46E5',
    logo: '/programs/child-in-the-world/logo.svg',
    heroImageUrl: 'https://images.unsplash.com/photo-1516383607781-913a19294fd1?w=1200&h=720&fit=crop',
    status: 'active',
    isPublic: true,
    createdAt: '2025-03-10T09:00:00.000Z',
    updatedAt: '2025-03-20T11:00:00.000Z',
    createdBy: 'partner-user-unicef-coordination',
  },
  {
    id: 'program-uk-climate-2025',
    partnerId: 'partner-unicef-england',
    displayTitle: 'UNICEF UK: Climate Action',
    name: 'UNICEF UK: Climate Action',
    marketingTagline: 'Cross-country climate labs connecting UK classrooms with global peers.',
    description:
      'Students investigate local climate challenges, compare with partner schools abroad, and co-design action sprints with community presentations and impact tracking.',
    projectTypes: ['explore_global_challenges', 'create_solutions'],
    pedagogicalFramework: ['pbl', 'design_thinking', 'global_citizenship'],
    learningGoals:
      'Help students build climate literacy, collaborate internationally, and prototype measurable climate actions in their communities.',
    targetAgeRanges: ['12-14', '15-18'],
    countriesInScope: ['UK', 'KE', 'BD'],
    sdgFocus: [13, 4, 17],
    crcFocus: ['24'],
    startDate: '2025-03-01',
    endDate: '2025-12-15',
    programUrl: 'https://prototype.class2class.org/programs/climate-action-labs',
    brandColor: '#3B82F6',
    logo: '/programs/climate-action-labs/logo.svg',
    heroImageUrl:
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&h=720&fit=crop',
    status: 'active',
    isPublic: true,
    createdAt: '2025-02-10T09:00:00.000Z',
    updatedAt: '2025-03-10T11:00:00.000Z',
    createdBy: 'partner-user-unicef-coordination',
  },
]

const buildSeedProgramPartners = (): PrototypeDatabase['programPartners'] => [
  {
    id: 'program-partner-build-change-host',
    programId: 'program-build-the-change-2025',
    partnerId: 'partner-save-the-children',
    role: 'host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: true,
    },
    invitedBy: 'partner-user-stc-director',
    invitedAt: '2025-01-05T08:05:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-01-05T08:05:00.000Z',
    createdAt: '2025-01-05T08:05:00.000Z',
    updatedAt: '2025-03-05T12:10:00.000Z',
  },
  {
    id: 'program-partner-build-change-lego',
    programId: 'program-build-the-change-2025',
    partnerId: 'partner-lego-foundation',
    role: 'co_host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: false,
    },
    invitedBy: 'partner-user-lego-lead',
    invitedAt: '2025-01-06T09:20:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-01-06T11:45:00.000Z',
    createdAt: '2025-01-06T09:20:00.000Z',
    updatedAt: '2025-02-18T07:55:00.000Z',
  },
  {
    id: 'program-partner-communities-host',
    programId: 'program-communities-2025',
    partnerId: 'partner-unicef',
    role: 'host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: true,
    },
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-01-20T09:05:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-01-20T09:05:00.000Z',
    createdAt: '2025-01-20T09:05:00.000Z',
    updatedAt: '2025-03-06T11:15:00.000Z',
  },
  {
    id: 'program-partner-communities-alm',
    programId: 'program-communities-2025',
    partnerId: 'partner-alm-brand',
    role: 'sponsor',
    permissions: {
      canEditProgram: false,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: false,
      canRemoveParticipants: false,
    },
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-01-21T08:20:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-01-22T07:45:00.000Z',
    createdAt: '2025-01-21T08:20:00.000Z',
    updatedAt: '2025-02-28T10:30:00.000Z',
  },
  {
    id: 'program-partner-child-world-host',
    programId: 'program-child-world-2025',
    partnerId: 'partner-unicef',
    role: 'host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: true,
    },
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-03-10T09:05:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-03-10T09:05:00.000Z',
    createdAt: '2025-03-10T09:05:00.000Z',
    updatedAt: '2025-03-20T11:00:00.000Z',
  },
  {
    id: 'program-partner-child-world-uk',
    programId: 'program-child-world-2025',
    partnerId: 'partner-unicef-england',
    role: 'co_host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: true,
    },
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-03-10T09:15:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-03-10T11:00:00.000Z',
    createdAt: '2025-03-10T09:15:00.000Z',
    updatedAt: '2025-03-20T11:00:00.000Z',
  },
  {
    id: 'program-partner-climate-uk-host',
    programId: 'program-uk-climate-2025',
    partnerId: 'partner-unicef-england',
    role: 'host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: true,
    },
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-02-10T09:05:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-02-10T09:05:00.000Z',
    createdAt: '2025-02-10T09:05:00.000Z',
    updatedAt: '2025-03-10T11:00:00.000Z',
  },
]

const buildSeedCoordinators = (): PrototypeDatabase['coordinators'] => [
  {
    id: 'coordinator-build-change-brazil',
    programId: 'program-build-the-change-2025',
    userId: 'partner-user-lego-lead',
    country: 'BR',
    region: 'São Paulo',
    email: 'buildchange.br@legofoundation.org',
    firstName: 'Renata',
    lastName: 'Silva',
    phoneNumber: '+55 11 5555 4321',
    status: 'active',
    invitedBy: 'partner-user-lego-lead',
    invitedAt: '2025-01-12T10:15:00.000Z',
    acceptedAt: '2025-01-13T08:00:00.000Z',
    createdAt: '2025-01-12T10:15:00.000Z',
    updatedAt: '2025-03-01T09:30:00.000Z',
  },
  {
    id: 'coordinator-build-change-india',
    programId: 'program-build-the-change-2025',
    userId: 'partner-user-stc-director',
    country: 'IN',
    region: 'Karnataka',
    email: 'buildchange.in@savethechildren.org',
    firstName: 'Anika',
    lastName: 'Rao',
    phoneNumber: '+91 80 1234 5678',
    status: 'invited',
    invitedBy: 'partner-user-lego-lead',
    invitedAt: '2025-02-05T07:30:00.000Z',
    createdAt: '2025-02-05T07:30:00.000Z',
    updatedAt: '2025-02-20T09:00:00.000Z',
  },
  {
    id: 'coordinator-communities-denmark',
    programId: 'program-communities-2025',
    userId: 'partner-user-unicef-coordination',
    country: 'DK',
    region: 'Capital Region',
    email: 'Mettev.dk@unicef.org',
    firstName: 'Mette',
    lastName: 'Victoria',
    phoneNumber: '+45 33 77 66 55',
    status: 'active',
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-01-24T09:45:00.000Z',
    acceptedAt: '2025-01-24T11:00:00.000Z',
    createdAt: '2025-01-24T09:45:00.000Z',
    updatedAt: '2025-03-03T08:30:00.000Z',
  },
  {
    id: 'coordinator-child-world-uk',
    programId: 'program-child-world-2025',
    userId: 'partner-user-unicef-coordination',
    country: 'UK',
    region: 'Greater Manchester',
    email: 'communities.uk@unicef.org',
    firstName: 'Eleanor',
    lastName: 'Shaw',
    phoneNumber: '+44 161 555 0192',
    status: 'invited',
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-02-15T10:20:00.000Z',
    createdAt: '2025-02-15T10:20:00.000Z',
    updatedAt: '2025-03-01T07:50:00.000Z',
  },
  {
    id: 'coordinator-child-world-denmark',
    programId: 'program-child-world-2025',
    userId: 'partner-user-unicef-coordination',
    country: 'DK',
    region: 'Capital Region',
    email: 'Mettev.dk@unicef.org',
    firstName: 'Mette',
    lastName: 'Victoria',
    phoneNumber: '+45 33 77 66 55',
    status: 'active',
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-03-12T09:45:00.000Z',
    acceptedAt: '2025-03-12T11:00:00.000Z',
    createdAt: '2025-03-12T09:45:00.000Z',
    updatedAt: '2025-03-20T08:30:00.000Z',
  },
  {
    id: 'coordinator-climate-uk',
    programId: 'program-uk-climate-2025',
    userId: 'partner-user-unicef-coordination',
    country: 'UK',
    region: 'Greater London',
    email: 'climate.uk@unicef.org',
    firstName: 'Amelia',
    lastName: 'Parker',
    phoneNumber: '+44 20 7946 1234',
    status: 'active',
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-02-12T09:45:00.000Z',
    acceptedAt: '2025-02-12T11:00:00.000Z',
    createdAt: '2025-02-12T09:45:00.000Z',
    updatedAt: '2025-03-03T08:30:00.000Z',
  },
]

const buildSeedInstitutions = (): PrototypeDatabase['institutions'] => [
  {
    id: 'institution-punti-luce-palermo',
    programId: 'program-build-the-change-2025',
    coordinatorId: 'coordinator-build-change-brazil',
    name: 'Punto Luce Palermo',
    type: 'primary_school',
    country: 'IT',
    region: 'Sicilia',
    city: 'Palermo',
    address: 'Via Regione Siciliana 20',
    contactEmail: 'coordinamento@puntolucepalermo.it',
    contactPhone: '+39 091 555 2233',
    principalName: 'Chiara Romano',
    principalEmail: 'chiara.romano@puntolucepalermo.it',
    studentCount: 420,
    teacherCount: 28,
    educationLevels: ['primary'],
    languages: ['it'],
    status: 'active',
    invitedAt: '2025-02-05T13:00:00.000Z',
    joinedAt: '2025-02-07T10:45:00.000Z',
    createdAt: '2025-02-05T13:00:00.000Z',
    updatedAt: '2025-03-01T09:35:00.000Z',
  },
  {
    id: 'institution-mexico-city-creative',
    programId: 'program-build-the-change-2025',
    coordinatorId: 'coordinator-build-change-brazil',
    name: 'Escuela Creativa CDMX',
    type: 'primary_school',
    country: 'MX',
    region: 'Ciudad de México',
    city: 'Mexico City',
    address: 'Av. Reforma 300',
    contactEmail: 'contacto@escuelacreativacdmx.mx',
    contactPhone: '+52 55 5555 1234',
    principalName: 'Carla Hernández',
    principalEmail: 'carla@escuelacreativacdmx.mx',
    studentCount: 520,
    teacherCount: 36,
    educationLevels: ['primary'],
    languages: ['es', 'en'],
    status: 'active',
    invitedAt: '2025-02-08T09:20:00.000Z',
    joinedAt: '2025-02-10T08:00:00.000Z',
    createdAt: '2025-02-08T09:20:00.000Z',
    updatedAt: '2025-02-27T11:10:00.000Z',
  },
  {
    id: 'institution-sao-paulo-makerspace',
    programId: 'program-build-the-change-2025',
    coordinatorId: 'coordinator-build-change-brazil',
    name: 'São Paulo Makerspace School',
    type: 'primary_school',
    country: 'BR',
    region: 'São Paulo',
    city: 'São Paulo',
    address: 'Av. Paulista 1000',
    contactEmail: 'coordinator@spmakers.edu.br',
    contactPhone: '+55 11 4002 8922',
    principalName: 'Camila Nogueira',
    principalEmail: 'camila@spmakers.edu.br',
    studentCount: 420,
    teacherCount: 28,
    educationLevels: ['primary'],
    languages: ['pt', 'en'],
    status: 'active',
    invitedAt: '2025-01-20T09:00:00.000Z',
    joinedAt: '2025-01-22T08:45:00.000Z',
    createdAt: '2025-01-20T09:00:00.000Z',
    updatedAt: '2025-02-15T10:00:00.000Z',
  },
  {
    id: 'institution-copenhagen-playlab',
    programId: 'program-build-the-change-2025',
    coordinatorId: 'coordinator-build-change-brazil',
    name: 'Copenhagen PlayLab',
    type: 'primary_school',
    country: 'DK',
    region: 'Capital Region',
    city: 'Copenhagen',
    address: 'Playful Learning Street 12',
    contactEmail: 'hello@playlab.dk',
    contactPhone: '+45 32 12 56 78',
    principalName: 'Mikkel Sørensen',
    principalEmail: 'mikkel@playlab.dk',
    studentCount: 310,
    teacherCount: 24,
    educationLevels: ['primary'],
    languages: ['da', 'en'],
    status: 'invited',
    invitedAt: '2025-02-10T10:40:00.000Z',
    createdAt: '2025-02-10T10:40:00.000Z',
    updatedAt: '2025-02-18T09:25:00.000Z',
  },
  {
    id: 'institution-london-climate-academy',
    programId: 'program-uk-climate-2025',
    coordinatorId: 'coordinator-climate-uk',
    name: 'London Climate Academy',
    type: 'secondary_school',
    country: 'UK',
    region: 'Greater London',
    city: 'London',
    address: '12 Thames Learning Way',
    contactEmail: 'contact@londonclimateacademy.uk',
    contactPhone: '+44 20 7000 2211',
    principalName: 'Rebecca Collins',
    principalEmail: 'rebecca.collins@londonclimateacademy.uk',
    studentCount: 620,
    teacherCount: 48,
    educationLevels: ['secondary'],
    languages: ['en'],
    status: 'active',
    invitedAt: '2025-02-25T09:30:00.000Z',
    joinedAt: '2025-02-27T10:00:00.000Z',
    createdAt: '2025-02-25T09:30:00.000Z',
    updatedAt: '2025-03-05T08:45:00.000Z',
  },
  {
    id: 'institution-bristol-green-school',
    programId: 'program-uk-climate-2025',
    coordinatorId: 'coordinator-climate-uk',
    name: 'Bristol Green School',
    type: 'secondary_school',
    country: 'UK',
    region: 'South West England',
    city: 'Bristol',
    address: '45 Avon Eco Lane',
    contactEmail: 'hello@bristolgreen.school',
    contactPhone: '+44 117 555 0909',
    principalName: 'Daniel Hughes',
    principalEmail: 'daniel.hughes@bristolgreen.school',
    studentCount: 540,
    teacherCount: 41,
    educationLevels: ['secondary'],
    languages: ['en'],
    status: 'invited',
    invitedAt: '2025-03-01T11:15:00.000Z',
    createdAt: '2025-03-01T11:15:00.000Z',
    updatedAt: '2025-03-05T09:10:00.000Z',
  },
  {
    id: 'institution-morke-rettighedsskole',
    programId: 'program-communities-2025',
    coordinatorId: 'coordinator-communities-denmark',
    name: 'Mørke Rettighedsskole',
    type: 'secondary_school',
    country: 'DK',
    region: 'Central Denmark',
    city: 'Mørke',
    address: 'Rettighedsvej 7',
    contactEmail: 'kontakt@morkerettighedsskole.dk',
    contactPhone: '+45 87 12 34 56',
    principalName: 'Karen Vester',
    principalEmail: 'karen.vester@morkerettighedsskole.dk',
    studentCount: 380,
    teacherCount: 29,
    educationLevels: ['secondary'],
    languages: ['da', 'en'],
    status: 'invited',
    invitedAt: '2025-03-18T10:15:00.000Z',
    createdAt: '2025-03-18T10:15:00.000Z',
    updatedAt: '2025-03-20T09:00:00.000Z',
  },
  {
    id: 'institution-christianhavns-rettighedsskole',
    programId: 'program-communities-2025',
    coordinatorId: 'coordinator-communities-denmark',
    name: 'Christianhavns rettighedskole',
    type: 'secondary_school',
    country: 'DK',
    region: 'Capital Region',
    city: 'Copenhagen',
    address: 'Christianhavns Torv 10',
    contactEmail: 'kontakt@christianhavnsrettighedskole.dk',
    contactPhone: '+45 33 22 11 00',
    principalName: 'Mikkel Pedersen',
    principalEmail: 'mikkel.pedersen@christianhavnsrettighedskole.dk',
    studentCount: 540,
    teacherCount: 42,
    educationLevels: ['secondary'],
    languages: ['da', 'en'],
    status: 'active',
    invitedAt: '2025-02-05T11:15:00.000Z',
    joinedAt: '2025-02-06T09:20:00.000Z',
    createdAt: '2025-02-05T11:15:00.000Z',
    updatedAt: '2025-03-02T10:05:00.000Z',
  },
  {
    id: 'institution-vesterbjerg-rettighedsskole',
    programId: 'program-communities-2025',
    coordinatorId: 'coordinator-communities-denmark',
    name: 'Vesterbjerg Rettighedsskole',
    type: 'secondary_school',
    country: 'DK',
    region: 'North Denmark',
    city: 'Aalborg',
    address: 'Vesterbjerg Allé 12',
    contactEmail: 'info@vesterbjergrettighedsskole.dk',
    contactPhone: '+45 98 44 22 11',
    principalName: 'Lars Mikkelsen',
    principalEmail: 'lars.mikkelsen@vesterbjergrettighedsskole.dk',
    studentCount: 420,
    teacherCount: 32,
    educationLevels: ['secondary'],
    languages: ['da', 'en'],
    status: 'active',
    invitedAt: '2025-03-18T11:00:00.000Z',
    joinedAt: '2025-03-20T10:30:00.000Z',
    createdAt: '2025-03-18T11:00:00.000Z',
    updatedAt: '2025-03-20T09:30:00.000Z',
  },
  {
    id: 'institution-manchester-community-school',
    programId: 'program-child-world-2025',
    coordinatorId: 'coordinator-child-world-uk',
    name: 'Manchester Rights School',
    type: 'secondary_school',
    country: 'UK',
    region: 'Greater Manchester',
    city: 'Manchester',
    address: '14 Community Drive',
    contactEmail: 'contact@manchestercommunity.uk',
    contactPhone: '+44 161 555 2200',
    principalName: 'Sarah Collins',
    principalEmail: 'sarah.collins@manchestercommunity.uk',
    studentCount: 460,
    teacherCount: 33,
    educationLevels: ['secondary'],
    languages: ['en'],
    status: 'invited',
    invitedAt: '2025-02-18T08:40:00.000Z',
    createdAt: '2025-02-18T08:40:00.000Z',
    updatedAt: '2025-02-28T12:00:00.000Z',
  },
  {
    id: 'institution-norrebro-international',
    programId: 'program-child-world-2025',
    coordinatorId: 'coordinator-child-world-denmark',
    name: 'Christianhavns rettighedskole',
    type: 'secondary_school',
    country: 'DK',
    region: 'Capital Region',
    city: 'Copenhagen',
    address: 'Christianhavns Torv 10',
    contactEmail: 'kontakt@christianhavnsrettighedskole.dk',
    contactPhone: '+45 33 22 11 00',
    principalName: 'Mikkel Pedersen',
    principalEmail: 'mikkel.pedersen@christianhavnsrettighedskole.dk',
    studentCount: 380,
    teacherCount: 28,
    educationLevels: ['secondary'],
    languages: ['da', 'en'],
    status: 'active',
    invitedAt: '2025-03-15T09:00:00.000Z',
    joinedAt: '2025-03-16T10:30:00.000Z',
    createdAt: '2025-03-15T09:00:00.000Z',
    updatedAt: '2025-03-20T08:00:00.000Z',
  },
  {
    id: 'institution-orestad-gymnasium',
    programId: 'program-communities-2025',
    coordinatorId: 'coordinator-communities-denmark',
    name: 'Ørestad Gymnasium',
    type: 'public_school',
    country: 'DK',
    region: 'Capital Region',
    city: 'Copenhagen',
    address: 'Ørestads Boulevard 75',
    contactEmail: 'kontor@orestadgym.dk',
    contactPhone: '+45 32 54 89 00',
    principalName: 'Henrik Vestergaard',
    principalEmail: 'henrik.vestergaard@orestadgym.dk',
    studentCount: 850,
    teacherCount: 65,
    educationLevels: ['high_school'],
    languages: ['da', 'en'],
    status: 'active',
    invitedAt: '2025-01-15T09:00:00.000Z',
    joinedAt: '2025-01-17T10:30:00.000Z',
    createdAt: '2025-01-15T09:00:00.000Z',
    updatedAt: '2025-03-10T08:00:00.000Z',
  },
  {
    id: 'institution-orestad-gymnasium-btc',
    programId: 'program-build-the-change-2025',
    coordinatorId: 'coordinator-build-change-brazil',
    name: 'Ørestad Gymnasium',
    type: 'public_school',
    country: 'DK',
    region: 'Capital Region',
    city: 'Copenhagen',
    address: 'Ørestads Boulevard 75',
    contactEmail: 'kontor@orestadgym.dk',
    contactPhone: '+45 32 54 89 00',
    principalName: 'Henrik Vestergaard',
    principalEmail: 'henrik.vestergaard@orestadgym.dk',
    studentCount: 850,
    teacherCount: 65,
    educationLevels: ['high_school'],
    languages: ['da', 'en'],
    status: 'active',
    invitedAt: '2025-01-20T09:00:00.000Z',
    joinedAt: '2025-01-22T10:30:00.000Z',
    createdAt: '2025-01-20T09:00:00.000Z',
    updatedAt: '2025-03-10T08:00:00.000Z',
  },
  {
    id: 'institution-orestad-gymnasium-unicef',
    programId: 'program-child-world-2025',
    coordinatorId: 'coordinator-child-world-denmark',
    name: 'Ørestad Gymnasium',
    type: 'public_school',
    country: 'DK',
    region: 'Capital Region',
    city: 'Copenhagen',
    address: 'Ørestads Boulevard 75',
    contactEmail: 'kontor@orestadgym.dk',
    contactPhone: '+45 32 54 89 00',
    principalName: 'Henrik Vestergaard',
    principalEmail: 'henrik.vestergaard@orestadgym.dk',
    studentCount: 850,
    teacherCount: 65,
    educationLevels: ['high_school'],
    languages: ['da', 'en'],
    status: 'active',
    invitedAt: '2025-02-01T09:00:00.000Z',
    joinedAt: '2025-02-03T10:30:00.000Z',
    createdAt: '2025-02-01T09:00:00.000Z',
    updatedAt: '2025-03-10T08:00:00.000Z',
  },
  {
    id: 'institution-bangalore-global-school',
    programId: 'program-build-the-change-2025',
    coordinatorId: 'coordinator-build-change-india',
    name: 'Bangalore Global School',
    type: 'public_school',
    country: 'IN',
    region: 'Karnataka',
    city: 'Bangalore',
    address: 'Koramangala 4th Block',
    contactEmail: 'contact@bangaloreglobal.edu.in',
    contactPhone: '+91 80 4123 5678',
    principalName: 'Priya Sharma',
    principalEmail: 'priya.sharma@bangaloreglobal.edu.in',
    studentCount: 680,
    teacherCount: 45,
    educationLevels: ['primary', 'secondary'],
    languages: ['en', 'hi'],
    status: 'active',
    invitedAt: '2025-02-10T08:00:00.000Z',
    joinedAt: '2025-02-12T10:00:00.000Z',
    createdAt: '2025-02-10T08:00:00.000Z',
    updatedAt: '2025-03-05T09:00:00.000Z',
  },
]

const buildSeedTeachers = (): PrototypeDatabase['institutionTeachers'] => [
  {
    id: 'teacher-sp-makers-lucas',
    institutionId: 'institution-sao-paulo-makerspace',
    programId: 'program-build-the-change-2025',
    email: 'lucas.souza@spmakers.edu.br',
    firstName: 'Lucas',
    lastName: 'Souza',
    subject: 'Environmental Science',
    gradeLevel: 'Primary',
    yearsExperience: 5,
    status: 'active',
    invitedAt: '2025-01-22T09:15:00.000Z',
    acceptedAt: '2025-01-22T11:30:00.000Z',
    createdAt: '2025-01-22T09:15:00.000Z',
    updatedAt: '2025-03-01T08:20:00.000Z',
  },
  {
    id: 'teacher-puntoluce-sara',
    institutionId: 'institution-punti-luce-palermo',
    programId: 'program-build-the-change-2025',
    email: 'sara.ricci@puntolucepalermo.it',
    firstName: 'Sara',
    lastName: 'Ricci',
    subject: 'Playful Learning',
    gradeLevel: 'Primary',
    yearsExperience: 6,
    status: 'active',
    invitedAt: '2025-01-25T09:30:00.000Z',
    acceptedAt: '2025-01-25T12:00:00.000Z',
    createdAt: '2025-01-25T09:30:00.000Z',
    updatedAt: '2025-03-03T07:55:00.000Z',
  },
  {
    id: 'teacher-cdmx-diego',
    institutionId: 'institution-mexico-city-creative',
    programId: 'program-build-the-change-2025',
    email: 'diego.martinez@escuelacreativacdmx.mx',
    firstName: 'Diego',
    lastName: 'Martínez',
    subject: 'Sustainability Lab',
    gradeLevel: 'Primary',
    yearsExperience: 4,
    status: 'invited',
    invitedAt: '2025-02-12T08:10:00.000Z',
    createdAt: '2025-02-12T08:10:00.000Z',
    updatedAt: '2025-02-26T09:45:00.000Z',
  },
  {
    id: 'teacher-aarhus-anne',
    institutionId: 'institution-orestad-gymnasium',
    programId: 'program-communities-2025',
    email: 'anne.holm@orestadgym.dk',
    firstName: 'Anne',
    lastName: 'Holm',
    subject: 'Social Studies',
    gradeLevel: 'Secondary',
    yearsExperience: 9,
    status: 'active',
    invitedAt: '2025-02-06T10:25:00.000Z',
    acceptedAt: '2025-02-06T12:10:00.000Z',
    createdAt: '2025-02-06T10:25:00.000Z',
    updatedAt: '2025-03-02T08:45:00.000Z',
  },
  {
    id: 'teacher-aarhus-karin',
    institutionId: 'institution-vesterbjerg-rettighedsskole',
    programId: 'program-communities-2025',
    email: 'karin.albrectsen@vesterbjergrettighedsskole.dk',
    firstName: 'Karin',
    lastName: 'Albrectsen',
    subject: 'Community Wellbeing',
    gradeLevel: 'Secondary',
    yearsExperience: 11,
    status: 'active',
    invitedAt: '2025-02-12T09:45:00.000Z',
    acceptedAt: '2025-02-12T11:15:00.000Z',
    createdAt: '2025-02-12T09:45:00.000Z',
    updatedAt: '2025-03-06T09:05:00.000Z',
  },
  {
    id: 'teacher-christianhavns-maja',
    institutionId: 'institution-norrebro-international',
    programId: 'program-child-world-2025',
    email: 'maja.sorensen@christianhavnsrettighedskole.dk',
    firstName: 'Maja',
    lastName: 'Sorensen',
    subject: 'Human Rights',
    gradeLevel: 'Secondary',
    yearsExperience: 8,
    status: 'active',
    invitedAt: '2025-02-14T09:00:00.000Z',
    acceptedAt: '2025-02-14T11:00:00.000Z',
    createdAt: '2025-02-14T09:00:00.000Z',
    updatedAt: '2025-03-08T09:20:00.000Z',
  },
  {
    id: 'teacher-morke-ulla',
    institutionId: 'institution-morke-rettighedsskole',
    programId: 'program-communities-2025',
    email: 'ulla.jensen@morkerettighedsskole.dk',
    firstName: 'Ulla',
    lastName: 'Jensen',
    subject: 'Civic Engagement',
    gradeLevel: 'Secondary',
    yearsExperience: 7,
    status: 'active',
    invitedAt: '2025-03-10T08:40:00.000Z',
    acceptedAt: '2025-03-10T10:00:00.000Z',
    createdAt: '2025-03-10T08:40:00.000Z',
    updatedAt: '2025-03-18T09:20:00.000Z',
  },
  {
    id: 'teacher-vesterbjerg-lars',
    institutionId: 'institution-vesterbjerg-rettighedsskole',
    programId: 'program-communities-2025',
    email: 'lars.nielsen@vesterbjergrettighedsskole.dk',
    firstName: 'Lars',
    lastName: 'Nielsen',
    subject: 'Community Studies',
    gradeLevel: 'Secondary',
    yearsExperience: 12,
    status: 'active',
    invitedAt: '2025-03-19T09:00:00.000Z',
    acceptedAt: '2025-03-19T11:30:00.000Z',
    createdAt: '2025-03-19T09:00:00.000Z',
    updatedAt: '2025-03-20T08:00:00.000Z',
  },
  {
    id: 'teacher-manchester-emily',
    institutionId: 'institution-manchester-community-school',
    programId: 'program-child-world-2025',
    email: 'emily.harper@manchestercommunity.uk',
    firstName: 'Emily',
    lastName: 'Harper',
    subject: 'Community Projects',
    gradeLevel: 'Secondary',
    yearsExperience: 8,
    status: 'active',
    invitedAt: '2025-02-18T09:10:00.000Z',
    acceptedAt: '2025-02-19T10:00:00.000Z',
    createdAt: '2025-02-18T09:10:00.000Z',
    updatedAt: '2025-02-28T11:40:00.000Z',
  },
  {
    id: 'teacher-norrebro-katrine',
    institutionId: 'institution-norrebro-international',
    programId: 'program-child-world-2025',
    email: 'katrine.berg@christianhavnsrettighedskole.dk',
    firstName: 'Katrine',
    lastName: 'Berg',
    subject: 'Global Citizenship',
    gradeLevel: 'Secondary',
    yearsExperience: 6,
    status: 'active',
    invitedAt: '2025-03-16T10:00:00.000Z',
    acceptedAt: '2025-03-16T14:30:00.000Z',
    createdAt: '2025-03-16T10:00:00.000Z',
    updatedAt: '2025-03-20T09:00:00.000Z',
  },
  {
    id: 'teacher-cph-global-jonas',
    institutionId: 'institution-norrebro-international',
    programId: 'program-child-world-2025',
    email: 'jonas.madsen@christianhavnsrettighedskole.dk',
    firstName: 'Jonas',
    lastName: 'Madsen',
    subject: 'Global Citizenship',
    gradeLevel: 'Secondary',
    yearsExperience: 10,
    status: 'active',
    invitedAt: '2025-03-18T10:10:00.000Z',
    acceptedAt: '2025-03-19T09:00:00.000Z',
    createdAt: '2025-03-18T10:10:00.000Z',
    updatedAt: '2025-03-20T09:40:00.000Z',
  },
  {
    id: 'teacher-aarhus-anne-build-change',
    institutionId: 'institution-orestad-gymnasium-btc',
    programId: 'program-build-the-change-2025',
    email: 'anne.holm@orestadgym.dk',
    firstName: 'Anne',
    lastName: 'Holm',
    subject: 'Social Studies',
    gradeLevel: 'Secondary',
    yearsExperience: 9,
    status: 'active',
    invitedAt: '2025-02-01T09:15:00.000Z',
    acceptedAt: '2025-02-01T11:20:00.000Z',
    createdAt: '2025-02-01T09:15:00.000Z',
    updatedAt: '2025-03-01T10:30:00.000Z',
  },
  // Colleagues at Ørestad Gymnasium
  {
    id: 'teacher-orestad-sofie',
    institutionId: 'institution-orestad-gymnasium',
    programId: 'program-communities-2025',
    email: 'sofie.larsen@orestadgym.dk',
    firstName: 'Sofie',
    lastName: 'Larsen',
    subject: 'English & Languages',
    gradeLevel: 'Secondary',
    yearsExperience: 7,
    status: 'active',
    invitedAt: '2025-01-22T10:15:00.000Z',
    acceptedAt: '2025-01-22T16:00:00.000Z',
    createdAt: '2025-01-22T10:15:00.000Z',
    updatedAt: '2025-03-05T09:20:00.000Z',
  },
  {
    id: 'teacher-orestad-peter',
    institutionId: 'institution-orestad-gymnasium-btc',
    programId: 'program-build-the-change-2025',
    email: 'peter.andersen@orestadgym.dk',
    firstName: 'Peter',
    lastName: 'Andersen',
    subject: 'Science & Technology',
    gradeLevel: 'Secondary',
    yearsExperience: 15,
    status: 'active',
    invitedAt: '2025-02-05T08:30:00.000Z',
    acceptedAt: '2025-02-05T12:00:00.000Z',
    createdAt: '2025-02-05T08:30:00.000Z',
    updatedAt: '2025-03-10T10:15:00.000Z',
  },
  {
    id: 'teacher-orestad-anne',
    institutionId: 'institution-orestad-gymnasium-unicef',
    programId: 'program-child-world-2025',
    email: 'anne.holm@orestadgym.dk',
    firstName: 'Anne',
    lastName: 'Holm',
    subject: 'Global Studies',
    gradeLevel: 'Secondary',
    yearsExperience: 8,
    status: 'active',
    invitedAt: '2025-02-03T10:00:00.000Z',
    acceptedAt: '2025-02-04T09:10:00.000Z',
    createdAt: '2025-02-03T10:00:00.000Z',
    updatedAt: '2025-03-05T10:00:00.000Z',
  },
  // Raj Patel - Bangalore Global School
  {
    id: 'teacher-bangalore-raj',
    institutionId: 'institution-bangalore-global-school',
    programId: 'program-build-the-change-2025',
    email: 'raj.patel@bangaloreglobal.edu.in',
    firstName: 'Raj',
    lastName: 'Patel',
    subject: 'Environmental Science',
    gradeLevel: 'Primary',
    yearsExperience: 8,
    status: 'active',
    invitedAt: '2025-02-15T09:00:00.000Z',
    acceptedAt: '2025-02-15T14:30:00.000Z',
    createdAt: '2025-02-15T09:00:00.000Z',
    updatedAt: '2025-03-08T10:00:00.000Z',
  },
  // Maria Garcia - Mexico City Creative School
  {
    id: 'teacher-cdmx-maria',
    institutionId: 'institution-mexico-city-creative',
    programId: 'program-build-the-change-2025',
    email: 'maria.garcia@escuelacreativacdmx.mx',
    firstName: 'Maria',
    lastName: 'Garcia',
    subject: 'Creative Arts & Design',
    gradeLevel: 'Primary',
    yearsExperience: 6,
    status: 'active',
    invitedAt: '2025-02-18T10:00:00.000Z',
    acceptedAt: '2025-02-18T15:00:00.000Z',
    createdAt: '2025-02-18T10:00:00.000Z',
    updatedAt: '2025-03-10T09:30:00.000Z',
  },
]

const buildSeedProjects = (): PrototypeDatabase['programProjects'] => [
  {
    id: 'program-project-build-change-city',
    programId: 'program-build-the-change-2025',
    projectId: 'project-build-change-city',
    templateId: 'template-build-change-city-guardians',
    createdByType: 'teacher',
    createdById: 'teacher-sp-makers-lucas',
    associatedCoPartnerId: 'program-partner-build-change-lego',
    status: 'active',
    coverImageUrl: 'https://images.unsplash.com/photo-1529101091764-c3526daf38fe?w=800&h=480&fit=crop',
    createdAt: '2025-02-05T13:20:00.000Z',
    updatedAt: '2025-03-01T09:00:00.000Z',
  },
  {
    id: 'program-project-build-change-ocean',
    programId: 'program-build-the-change-2025',
    projectId: 'project-build-change-ocean',
    templateId: 'template-build-change-ocean-stewards',
    createdByType: 'teacher',
    createdById: 'teacher-sp-makers-lucas',
    status: 'draft',
    coverImageUrl: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=480&fit=crop',
    createdAt: '2025-02-18T10:05:00.000Z',
    updatedAt: '2025-02-18T10:05:00.000Z',
  },
  {
    id: 'program-project-build-change-garden',
    programId: 'program-build-the-change-2025',
    projectId: 'project-build-change-garden',
    templateId: 'template-build-change-school-garden',
    createdByType: 'teacher',
    createdById: 'teacher-aarhus-anne-build-change',
    associatedCoPartnerId: 'program-partner-build-change-lego',
    status: 'active',
    coverImageUrl: '/images/lego-garden-school.png',
    createdAt: '2025-02-20T12:30:00.000Z',
    updatedAt: '2025-03-05T09:50:00.000Z',
  },
  {
    id: 'program-project-communities-belonging',
    programId: 'program-communities-2025',
    projectId: 'project-communities-belonging',
    templateId: 'template-communities-belonging-circles',
    createdByType: 'teacher',
    createdById: 'teacher-aarhus-karin',
    status: 'active',
    coverImageUrl: '/images/community-inclusion.png',
    createdAt: '2025-02-15T11:20:00.000Z',
    updatedAt: '2025-03-04T10:15:00.000Z',
  },
  {
    id: 'program-project-communities-belonging-ulla',
    programId: 'program-communities-2025',
    projectId: 'project-communities-belonging-ulla',
    templateId: 'template-communities-belonging-circles',
    createdByType: 'teacher',
    createdById: 'teacher-morke-ulla',
    participantIds: ['teacher-aarhus-anne'], // Anne Holm joined this project
    status: 'active',
    coverImageUrl: '/images/community-inclusion.png',
    createdAt: '2025-03-12T09:30:00.000Z',
    updatedAt: '2025-03-12T09:30:00.000Z',
  },
  {
    id: 'program-project-communities-action',
    programId: 'program-communities-2025',
    projectId: 'project-communities-action',
    templateId: 'template-communities-action-lab',
    createdByType: 'teacher',
    createdById: 'teacher-aarhus-anne',
    status: 'active',
    coverImageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=480&fit=crop',
    createdAt: '2025-03-02T08:15:00.000Z',
    updatedAt: '2025-03-02T08:15:00.000Z',
  },
  {
    id: 'program-project-child-world-story',
    programId: 'program-child-world-2025',
    projectId: 'project-child-world-story',
    templateId: 'template-child-world-story-exchange',
    createdByType: 'teacher',
    createdById: 'teacher-manchester-emily',
    status: 'active',
    coverImageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=480&fit=crop',
    createdAt: '2025-03-18T12:10:00.000Z',
    updatedAt: '2025-03-20T09:20:00.000Z',
  },
  {
    id: 'program-project-child-world-rights',
    programId: 'program-child-world-2025',
    projectId: 'project-child-world-rights',
    templateId: 'template-child-world-action-sprint',
    createdByType: 'teacher',
    createdById: 'teacher-cph-global-jonas',
    status: 'active',
    coverImageUrl: 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?w=800&h=480&fit=crop',
    createdAt: '2025-03-20T14:00:00.000Z',
    updatedAt: '2025-03-20T14:00:00.000Z',
  },
]

const buildSeedProgramTemplates = (): PrototypeDatabase['programTemplates'] => [
  {
    id: 'template-build-change-city-guardians',
    programId: 'program-build-the-change-2025',
    title: 'City Guardians Workshop',
    summary:
      'Children redesign public spaces using LEGO bricks, focusing on clean energy, green transport, and playful community hubs.',
    heroImageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=480&fit=crop',
    estimatedDurationWeeks: 4,
    recommendedStartMonth: 'September',
    subjectFocus: ['science', 'design'],
    sdgAlignment: [7, 11, 13],
    requiredMaterials: ['LEGO bricks', 'Local city map', 'Storytelling board'],
    languageSupport: ['en', 'pt'],
    isActive: true,
    createdAt: '2025-01-07T09:00:00.000Z',
    updatedAt: '2025-02-21T12:00:00.000Z',
  },
  {
    id: 'template-build-change-ocean-stewards',
    programId: 'program-build-the-change-2025',
    title: 'Ocean Stewards Lab',
    summary:
      'Learners investigate plastic waste issues, prototype cleanup inventions, and pitch campaigns to protect local waterways.',
    heroImageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800&h=480&fit=crop',
    estimatedDurationWeeks: 3,
    recommendedStartMonth: 'March',
    subjectFocus: ['science', 'civics'],
    sdgAlignment: [6, 12, 14],
    requiredMaterials: ['LEGO bricks', 'Micro:bit kits', 'Interview guides'],
    languageSupport: ['en', 'da', 'pt'],
    isActive: true,
    createdAt: '2025-01-08T10:15:00.000Z',
    updatedAt: '2025-02-12T15:10:00.000Z',
  },
  {
    id: 'template-communities-story-circle',
    programId: 'program-communities-2025',
    title: 'Community Story Circles',
    summary:
      'Students host guided conversations to surface stories about belonging, synthesise insights, and prepare visual narratives to share with partner classes.',
    heroImageUrl: 'https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?w=800&h=480&fit=crop',
    estimatedDurationWeeks: 3,
    recommendedStartMonth: 'February',
    subjectFocus: ['civics', 'language'],
    sdgAlignment: [3, 11],
    requiredMaterials: ['Conversation guides', 'Story cards', 'Digital recorder'],
    languageSupport: ['da', 'es', 'en'],
    isActive: true,
    createdAt: '2025-01-23T09:30:00.000Z',
    updatedAt: '2025-02-28T07:40:00.000Z',
  },
  {
    id: 'template-communities-action-lab',
    programId: 'program-communities-2025',
    title: 'Community Action Lab',
    summary:
      'Classes prototype small actions that strengthen inclusion—such as welcome rituals or peer support systems—and iterate based on feedback from partner schools.',
    heroImageUrl: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=800&h=480&fit=crop',
    estimatedDurationWeeks: 4,
    recommendedStartMonth: 'April',
    subjectFocus: ['design', 'social_sciences'],
    sdgAlignment: [3, 4, 11],
    requiredMaterials: ['Design thinking canvas', 'Feedback forms', 'LEGO bricks'],
    languageSupport: ['en', 'da', 'es'],
    isActive: true,
    createdAt: '2025-01-24T11:10:00.000Z',
    updatedAt: '2025-03-03T08:20:00.000Z',
  },
  {
    id: 'template-build-change-school-garden',
    programId: 'program-build-the-change-2025',
    title: 'Sustainable School Garden',
    summary:
      'Design and create a thriving school garden using LEGO bricks to prototype sustainable solutions. Work with partner classrooms to bring green spaces, renewable energy, and community gardening projects to life in your school.',
    heroImageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&h=480&fit=crop',
    estimatedDurationWeeks: 6,
    recommendedStartMonth: 'September',
    subjectFocus: ['science', 'design', 'sustainability'],
    sdgAlignment: [11, 13, 15],
    requiredMaterials: ['LEGO bricks', 'Garden planning tools', 'Sustainability guides'],
    languageSupport: ['en', 'da'],
    isActive: true,
    createdAt: '2025-01-10T09:00:00.000Z',
    updatedAt: '2025-02-15T10:30:00.000Z',
  },
  {
    id: 'template-communities-belonging-circles',
    programId: 'program-communities-2025',
    title: 'Building Belonging in Our Communities',
    summary:
      'Students explore what makes communities welcoming and inclusive through dialogue, storytelling, and collaborative problem-solving. Partner classrooms work together to identify barriers to belonging and co-create solutions that strengthen community connections and celebrate diversity.',
    heroImageUrl: 'https://images.unsplash.com/photo-1609619385002-f40f2a6eef93?w=800&h=480&fit=crop',
    estimatedDurationWeeks: 5,
    recommendedStartMonth: 'February',
    subjectFocus: ['civics', 'social_sciences', 'language'],
    sdgAlignment: [3, 10, 16],
    requiredMaterials: ['Discussion guides', 'Story collection tools', 'Community mapping materials'],
    languageSupport: ['en', 'da', 'es'],
    isActive: true,
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-02-20T14:30:00.000Z',
  },
  {
    id: 'template-child-world-story-exchange',
    programId: 'program-child-world-2025',
    title: 'Child Rights Story Exchange',
    summary:
      'Danish and British students swap weekly story prompts on rights, well-being, and belonging, then co-create a joint digital zine.',
    heroImageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&h=480&fit=crop',
    estimatedDurationWeeks: 3,
    recommendedStartMonth: 'May',
    subjectFocus: ['language', 'civics'],
    sdgAlignment: [4, 10, 16],
    requiredMaterials: ['Story prompts', 'Video messages', 'Digital zine templates'],
    languageSupport: ['en', 'da'],
    isActive: true,
    createdAt: '2025-03-12T10:00:00.000Z',
    updatedAt: '2025-03-20T11:00:00.000Z',
  },
  {
    id: 'template-child-world-action-sprint',
    programId: 'program-child-world-2025',
    title: 'Shared Action Sprint',
    summary:
      'Partner classes identify a children’s rights theme and prototype small actions they each run locally, then present combined impact highlights.',
    heroImageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=480&fit=crop',
    estimatedDurationWeeks: 4,
    recommendedStartMonth: 'September',
    subjectFocus: ['design', 'social_sciences'],
    sdgAlignment: [4, 10, 16],
    requiredMaterials: ['Action canvas', 'Feedback loops', 'Showcase deck'],
    languageSupport: ['en', 'da'],
    isActive: true,
    createdAt: '2025-03-12T11:00:00.000Z',
    updatedAt: '2025-03-20T11:00:00.000Z',
  },
]

const buildSeedInvitations = (): PrototypeDatabase['invitations'] => [
  {
    id: 'invitation-build-change-labcorp',
    programId: 'program-build-the-change-2025',
    invitationType: 'co_partner',
    recipientEmail: 'innovation@labcorp.org',
    recipientName: 'LabCorp Innovation Hub',
    sentBy: 'partner-user-lego-lead',
    sentByType: 'partner',
    customMessage:
      'We would love your creative technologists to mentor our young makers as they design sustainable cities.',
    token: 'c2c_invite_BUILDCHANGE_2025',
    expiresAt: '2025-05-15T23:59:59.000Z',
    status: 'pending',
    sentAt: '2025-03-05T08:30:00.000Z',
    createdAt: '2025-03-05T08:30:00.000Z',
    updatedAt: '2025-03-05T08:30:00.000Z',
    proposedRole: 'advisor',
    proposedPermissions: {
      canEditProgram: false,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: false,
      canRemoveParticipants: false,
    },
  },
  {
    id: 'invitation-communities-studentcouncil',
    programId: 'program-communities-2025',
    invitationType: 'coordinator',
    recipientEmail: 'council@vesterbjergrettighedsskole.dk',
    recipientName: 'Vesterbjerg Student Council',
    sentBy: 'partner-user-unicef-coordination',
    sentByType: 'partner',
    customMessage:
      'We are inviting you to co-lead the community action lab and share student voice from Vesterbjerg with our partner schools.',
    token: 'c2c_invite_COMMUNITY_2025',
    expiresAt: '2025-04-30T23:59:59.000Z',
    status: 'pending',
    sentAt: '2025-03-04T10:00:00.000Z',
    createdAt: '2025-03-04T10:00:00.000Z',
    updatedAt: '2025-03-04T10:00:00.000Z',
    assignedCountry: 'DK',
    assignedRegion: 'North Denmark',
  },
]

const buildSeedActivities = (): PrototypeDatabase['activities'] => [
  {
    id: 'activity-2025-02-12-build-change',
    programId: 'program-build-the-change-2025',
    type: 'project_created',
    actorName: 'Sara Ricci',
    actorType: 'teacher',
    description: 'Punto Luce Palermo students unveiled prototype models for their “City Guardians” playground redesign.',
    timestamp: '2025-02-12T15:20:00.000Z',
  },
  {
    id: 'activity-2025-02-28-build-change',
    programId: 'program-build-the-change-2025',
    type: 'institution_joined',
    actorName: 'Escuela Creativa CDMX',
    actorType: 'partner',
    description: 'CDMX Creative School activated their Build the Change classroom and scheduled their first design jam.',
    timestamp: '2025-02-28T09:40:00.000Z',
  },
  {
    id: 'activity-2025-03-04-communities',
    programId: 'program-communities-2025',
    type: 'project_created',
    actorName: 'Anne Holm',
    actorType: 'teacher',
    description: 'Vesterbjerg Rettighedsskole shared story-circle insights with partner classrooms in Manchester.',
    timestamp: '2025-03-04T11:05:00.000Z',
  },
]

const buildSeedDatabase = (): PrototypeDatabase => {
  const seededAt = new Date().toISOString()

  return {
    partners: buildSeedPartners(),
    partnerUsers: buildSeedPartnerUsers(),
    programs: buildSeedPrograms(),
    programPartners: buildSeedProgramPartners(),
    coordinators: buildSeedCoordinators(),
    institutions: buildSeedInstitutions(),
    institutionTeachers: buildSeedTeachers(),
    programProjects: buildSeedProjects(),
    programTemplates: buildSeedProgramTemplates(),
    invitations: buildSeedInvitations(),
    activities: buildSeedActivities(),
    metadata: {
      version: PROTOTYPE_SEED_VERSION,
      seededAt,
    },
  }
}

interface SeedOptions {
  force?: boolean
}

export const seedPrototypeDb = (options: SeedOptions = {}): {
  seeded: boolean
  reason?: 'already-seeded'
  database: PrototypeDatabase
} => {
  const current = loadPrototypeDb()

  if (!options.force) {
    const alreadySeeded = Boolean(current.metadata.seededAt) || current.programs.length > 0
    const isCurrentVersion = current.metadata.version === PROTOTYPE_SEED_VERSION

    if (alreadySeeded && isCurrentVersion) {
      return {
        seeded: false,
        reason: 'already-seeded',
        database: current,
      }
    }
  }

  const seededDb = buildSeedDatabase()
  persistPrototypeDb(seededDb)

  return {
    seeded: true,
    database: seededDb,
  }
}

export const getPrototypeSeedSnapshot = (): PrototypeDatabase => buildSeedDatabase()

export { PROTOTYPE_SEED_VERSION }
