import {
  loadPrototypeDb,
  persistPrototypeDb,
  PrototypeDatabase,
  StoredPartner,
  StoredPartnerUser,
} from '@/lib/storage/prototype-db'

const PROTOTYPE_SEED_VERSION = 1

const buildSeedPartners = (): StoredPartner[] => [
  {
    id: 'partner-save-the-children',
    organizationName: 'Save the Children International',
    organizationType: 'ngo',
    logo: '/partners/save-the-children.png',
    description: 'Global NGO focused on ensuring every child has the future they deserve.',
    mission: 'Create sustainable, child-centered programs that improve education and wellbeing worldwide.',
    website: 'https://www.savethechildren.net',
    contactEmail: 'partnerships@savethechildren.org',
    contactPhone: '+45 33 73 20 00',
    country: 'DK',
    languages: ['en', 'da'],
    sdgFocus: ['SDG 4', 'SDG 5', 'SDG 10'],
    createdAt: '2025-01-10T09:00:00.000Z',
    updatedAt: '2025-03-01T10:15:00.000Z',
    isActive: true,
    verificationStatus: 'verified',
  },
  {
    id: 'partner-lego-foundation',
    organizationName: 'LEGO Foundation',
    organizationType: 'commercial',
    logo: '/partners/lego-foundation.png',
    description: 'Philanthropic arm of LEGO Group supporting learning through play.',
    mission: 'Inspire and develop the builders of tomorrow through playful learning experiences.',
    website: 'https://www.legofoundation.com',
    contactEmail: 'partnerships@legofoundation.com',
    contactPhone: '+45 79 50 60 70',
    country: 'DK',
    languages: ['en', 'da'],
    sdgFocus: ['SDG 4', 'SDG 9'],
    createdAt: '2025-01-14T11:30:00.000Z',
    updatedAt: '2025-02-20T13:45:00.000Z',
    isActive: true,
    verificationStatus: 'verified',
  },
  {
    id: 'partner-unicef',
    organizationName: 'UNICEF Learning Lab',
    organizationType: 'ngo',
    logo: '/partners/unicef.png',
    description: 'UN agency delivering development programs with a focus on education equity.',
    mission: 'Advance children’s rights and equitable access to transformative learning programmes.',
    website: 'https://www.unicef.org',
    contactEmail: 'learninglab@unicef.org',
    contactPhone: '+41 22 909 50 11',
    country: 'CH',
    languages: ['en', 'fr', 'es'],
    sdgFocus: ['SDG 4', 'SDG 16', 'SDG 17'],
    createdAt: '2025-01-18T08:45:00.000Z',
    updatedAt: '2025-02-25T09:20:00.000Z',
    isActive: true,
    verificationStatus: 'verified',
  },
]

const buildSeedPartnerUsers = (): StoredPartnerUser[] => [
  {
    id: 'partner-user-stc-director',
    partnerId: 'partner-save-the-children',
    email: 'director@savethechildren.org',
    firstName: 'Amara',
    lastName: 'Jensen',
    role: 'admin',
    hasAcceptedTerms: true,
    twoFactorEnabled: true,
    createdAt: '2025-01-10T09:05:00.000Z',
    lastLoginAt: '2025-03-03T07:55:00.000Z',
    isActive: true,
  },
  {
    id: 'partner-user-lego-lead',
    partnerId: 'partner-lego-foundation',
    email: 'partnerships@legofoundation.com',
    firstName: 'Luca',
    lastName: 'Villadsen',
    role: 'collaborator',
    hasAcceptedTerms: true,
    twoFactorEnabled: false,
    createdAt: '2025-01-14T11:32:00.000Z',
    lastLoginAt: '2025-02-28T12:05:00.000Z',
    isActive: true,
  },
  {
    id: 'partner-user-unicef-coordination',
    partnerId: 'partner-unicef',
    email: 'coordinator@unicef.org',
    firstName: 'Naila',
    lastName: 'Rahman',
    role: 'collaborator',
    hasAcceptedTerms: true,
    twoFactorEnabled: true,
    createdAt: '2025-01-18T08:50:00.000Z',
    lastLoginAt: '2025-03-02T09:30:00.000Z',
    isActive: true,
  },
]

const buildSeedPrograms = (): PrototypeDatabase['programs'] => [
  {
    id: 'program-climate-changemakers-2025',
    partnerId: 'partner-save-the-children',
    name: 'Climate Changemakers 2025',
    description: 'Global student collaboration to co-design climate resilience solutions with local impact.',
    projectTypes: ['environmental_action', 'collaborative_project', 'service_learning'],
    pedagogicalFramework: ['pbl', 'esd', 'design_thinking'],
    learningGoals: 'Students investigate climate challenges, prototype solutions, and exchange cross-cultural insights.',
    targetAgeRanges: ['12-14', '15-18'],
    countriesInScope: ['DK', 'KE', 'US'],
    sdgFocus: [4, 10, 13],
    startDate: '2025-02-01',
    endDate: '2025-11-30',
    programUrl: 'https://prototype.class2class.org/programs/climate-changemakers-2025',
    brandColor: '#1F8A70',
    logo: '/programs/climate-changemakers/logo.png',
    status: 'active',
    isPublic: true,
    createdAt: '2025-01-22T09:00:00.000Z',
    updatedAt: '2025-03-02T10:40:00.000Z',
    createdBy: 'partner-user-stc-director',
  },
  {
    id: 'program-digital-bridges-2025',
    partnerId: 'partner-lego-foundation',
    name: 'Digital Bridges for Creative STEM',
    description: 'Regional partnership connecting schools through maker-based STEM challenges facilitated by LEGO play labs.',
    projectTypes: ['stem_challenge', 'virtual_classroom', 'collaborative_project'],
    pedagogicalFramework: ['steam', 'pbl', 'design_thinking'],
    learningGoals: 'Empower teachers to lead playful STEM experiences that develop computational thinking and creativity.',
    targetAgeRanges: ['9-11', '12-14'],
    countriesInScope: ['DK', 'BR', 'IN', 'ZA'],
    sdgFocus: [4, 8, 9],
    startDate: '2025-03-15',
    endDate: '2025-12-15',
    programUrl: 'https://prototype.class2class.org/programs/digital-bridges-2025',
    brandColor: '#F5971D',
    logo: '/programs/digital-bridges/logo.png',
    status: 'planning',
    isPublic: false,
    createdAt: '2025-02-05T14:10:00.000Z',
    updatedAt: '2025-03-04T16:20:00.000Z',
    createdBy: 'partner-user-lego-lead',
  },
]

const buildSeedProgramPartners = (): PrototypeDatabase['programPartners'] => [
  {
    id: 'program-partner-climate-host',
    programId: 'program-climate-changemakers-2025',
    partnerId: 'partner-save-the-children',
    role: 'host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: true,
    },
    invitedBy: 'partner-user-stc-director',
    invitedAt: '2025-01-22T09:05:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-01-22T09:05:00.000Z',
    createdAt: '2025-01-22T09:05:00.000Z',
    updatedAt: '2025-03-02T10:40:00.000Z',
  },
  {
    id: 'program-partner-climate-lego',
    programId: 'program-climate-changemakers-2025',
    partnerId: 'partner-lego-foundation',
    role: 'co_host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: false,
    },
    invitedBy: 'partner-user-stc-director',
    invitedAt: '2025-01-25T10:15:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-01-26T08:10:00.000Z',
    createdAt: '2025-01-25T10:15:00.000Z',
    updatedAt: '2025-02-27T11:30:00.000Z',
  },
  {
    id: 'program-partner-climate-unicef',
    programId: 'program-climate-changemakers-2025',
    partnerId: 'partner-unicef',
    role: 'advisor',
    permissions: {
      canEditProgram: false,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: false,
      canRemoveParticipants: false,
    },
    invitedBy: 'partner-user-stc-director',
    invitedAt: '2025-01-28T09:45:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-01-29T12:05:00.000Z',
    createdAt: '2025-01-28T09:45:00.000Z',
    updatedAt: '2025-02-15T07:55:00.000Z',
  },
  {
    id: 'program-partner-digital-host',
    programId: 'program-digital-bridges-2025',
    partnerId: 'partner-lego-foundation',
    role: 'host',
    permissions: {
      canEditProgram: true,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: true,
      canRemoveParticipants: true,
    },
    invitedBy: 'partner-user-lego-lead',
    invitedAt: '2025-02-05T14:12:00.000Z',
    status: 'accepted',
    acceptedAt: '2025-02-05T14:12:00.000Z',
    createdAt: '2025-02-05T14:12:00.000Z',
    updatedAt: '2025-03-04T16:20:00.000Z',
  },
]

const buildSeedCoordinators = (): PrototypeDatabase['coordinators'] => [
  {
    id: 'coordinator-climate-denmark',
    programId: 'program-climate-changemakers-2025',
    userId: 'partner-user-stc-director',
    country: 'DK',
    region: 'Capital Region',
    email: 'dk.coordinator@savethechildren.org',
    firstName: 'Katrine',
    lastName: 'Madsen',
    phoneNumber: '+45 40 55 12 34',
    status: 'active',
    invitedBy: 'partner-user-stc-director',
    invitedAt: '2025-01-30T08:00:00.000Z',
    acceptedAt: '2025-01-31T09:15:00.000Z',
    createdAt: '2025-01-30T08:00:00.000Z',
    updatedAt: '2025-03-03T07:50:00.000Z',
  },
  {
    id: 'coordinator-climate-kenya',
    programId: 'program-climate-changemakers-2025',
    userId: 'partner-user-unicef-coordination',
    country: 'KE',
    region: 'Nairobi County',
    email: 'ke.coordinator@unicef.org',
    firstName: 'Otieno',
    lastName: 'Mwangi',
    phoneNumber: '+254 720 555 210',
    status: 'active',
    invitedBy: 'partner-user-unicef-coordination',
    invitedAt: '2025-02-01T11:10:00.000Z',
    acceptedAt: '2025-02-02T08:05:00.000Z',
    createdAt: '2025-02-01T11:10:00.000Z',
    updatedAt: '2025-02-26T12:40:00.000Z',
  },
  {
    id: 'coordinator-climate-usa',
    programId: 'program-climate-changemakers-2025',
    userId: 'partner-user-stc-director',
    country: 'US',
    region: 'California',
    email: 'us.coordinator@savethechildren.org',
    firstName: 'Jordan',
    lastName: 'Nguyen',
    phoneNumber: '+1 415 555 0876',
    status: 'invited',
    invitedBy: 'partner-user-stc-director',
    invitedAt: '2025-02-20T15:30:00.000Z',
    createdAt: '2025-02-20T15:30:00.000Z',
    updatedAt: '2025-02-28T09:00:00.000Z',
  },
]

const buildSeedInstitutions = (): PrototypeDatabase['institutions'] => [
  {
    id: 'institution-orestad-gymnasium',
    programId: 'program-climate-changemakers-2025',
    coordinatorId: 'coordinator-climate-denmark',
    name: 'Ørestad Gymnasium',
    type: 'high_school',
    country: 'DK',
    region: 'Capital Region',
    city: 'Copenhagen',
    address: 'Ørestads Boulevard 75',
    contactEmail: 'principal@orestadgym.dk',
    contactPhone: '+45 32 46 29 00',
    principalName: 'Louise Enemark',
    principalEmail: 'len@orestadgym.dk',
    studentCount: 850,
    teacherCount: 65,
    educationLevels: ['high_school'],
    languages: ['da', 'en'],
    status: 'active',
    invitedAt: '2025-02-05T13:00:00.000Z',
    joinedAt: '2025-02-07T10:45:00.000Z',
    createdAt: '2025-02-05T13:00:00.000Z',
    updatedAt: '2025-03-01T09:35:00.000Z',
  },
  {
    id: 'institution-nairobi-school',
    programId: 'program-climate-changemakers-2025',
    coordinatorId: 'coordinator-climate-kenya',
    name: 'Nairobi School',
    type: 'high_school',
    country: 'KE',
    region: 'Nairobi County',
    city: 'Nairobi',
    address: 'Waiyaki Way',
    contactEmail: 'principal@nairobi-school.ac.ke',
    contactPhone: '+254 20 444 2233',
    principalName: 'Patrick Waweru',
    principalEmail: 'pwaweru@nairobi-school.ac.ke',
    studentCount: 1200,
    teacherCount: 80,
    educationLevels: ['high_school'],
    languages: ['en', 'sw'],
    status: 'active',
    invitedAt: '2025-02-08T09:20:00.000Z',
    joinedAt: '2025-02-10T08:00:00.000Z',
    createdAt: '2025-02-08T09:20:00.000Z',
    updatedAt: '2025-02-27T11:10:00.000Z',
  },
  {
    id: 'institution-san-jose-stem',
    programId: 'program-digital-bridges-2025',
    coordinatorId: 'coordinator-climate-usa',
    name: 'San Jose STEM Magnet',
    type: 'high_school',
    country: 'US',
    region: 'California',
    city: 'San Jose',
    address: '200 Innovation Drive',
    contactEmail: 'stemlead@sjusd.org',
    contactPhone: '+1 408 555 1200',
    principalName: 'Robyn Castillo',
    studentCount: 950,
    teacherCount: 72,
    educationLevels: ['high_school'],
    languages: ['en', 'es'],
    status: 'invited',
    invitedAt: '2025-03-01T16:10:00.000Z',
    createdAt: '2025-03-01T16:10:00.000Z',
    updatedAt: '2025-03-04T10:05:00.000Z',
  },
]

const buildSeedTeachers = (): PrototypeDatabase['institutionTeachers'] => [
  {
    id: 'teacher-orestad-astrid',
    institutionId: 'institution-orestad-gymnasium',
    programId: 'program-climate-changemakers-2025',
    email: 'astrid.larsen@orestadgym.dk',
    firstName: 'Astrid',
    lastName: 'Larsen',
    subject: 'Geography & Sustainability',
    gradeLevel: 'Upper Secondary',
    yearsExperience: 7,
    status: 'active',
    invitedAt: '2025-02-07T11:00:00.000Z',
    acceptedAt: '2025-02-07T14:30:00.000Z',
    createdAt: '2025-02-07T11:00:00.000Z',
    updatedAt: '2025-03-02T09:55:00.000Z',
  },
  {
    id: 'teacher-nairobi-school-lekan',
    institutionId: 'institution-nairobi-school',
    programId: 'program-climate-changemakers-2025',
    email: 'lekan.mutua@nairobi-school.ac.ke',
    firstName: 'Lekan',
    lastName: 'Mutua',
    subject: 'Biology',
    gradeLevel: 'Form 3',
    yearsExperience: 11,
    status: 'active',
    invitedAt: '2025-02-10T09:10:00.000Z',
    acceptedAt: '2025-02-10T12:45:00.000Z',
    createdAt: '2025-02-10T09:10:00.000Z',
    updatedAt: '2025-02-28T10:05:00.000Z',
  },
]

const buildSeedProjects = (): PrototypeDatabase['programProjects'] => [
  {
    id: 'program-project-climate-water-guardians',
    programId: 'program-climate-changemakers-2025',
    projectId: 'project-water-guardians',
    createdByType: 'teacher',
    createdById: 'teacher-orestad-astrid',
    associatedCoPartnerId: 'program-partner-climate-lego',
    status: 'active',
    createdAt: '2025-02-18T10:30:00.000Z',
    updatedAt: '2025-03-01T09:15:00.000Z',
  },
  {
    id: 'program-project-climate-tree-mappers',
    programId: 'program-climate-changemakers-2025',
    projectId: 'project-tree-mappers',
    createdByType: 'teacher',
    createdById: 'teacher-nairobi-school-lekan',
    status: 'draft',
    createdAt: '2025-02-24T11:45:00.000Z',
    updatedAt: '2025-02-24T11:45:00.000Z',
  },
]

const buildSeedInvitations = (): PrototypeDatabase['invitations'] => [
  {
    id: 'invitation-digital-bridges-habitat',
    programId: 'program-digital-bridges-2025',
    invitationType: 'co_partner',
    recipientEmail: 'partnerships@habitat.org',
    recipientName: 'Habitat for Humanity Global Programs',
    sentBy: 'partner-user-lego-lead',
    sentByType: 'partner',
    customMessage: 'We would love Habitat to co-design the community innovation sprint.',
    token: 'c2c_invite_HABITAT_2025',
    expiresAt: '2025-04-15T23:59:59.000Z',
    status: 'pending',
    sentAt: '2025-03-02T08:30:00.000Z',
    createdAt: '2025-03-02T08:30:00.000Z',
    updatedAt: '2025-03-02T08:30:00.000Z',
    proposedRole: 'advisor',
    proposedPermissions: {
      canEditProgram: false,
      canInviteCoordinators: true,
      canViewAllData: true,
      canManageProjects: false,
      canRemoveParticipants: false,
    },
  },
  {
    id: 'invitation-climate-usa-coordinator',
    programId: 'program-climate-changemakers-2025',
    invitationType: 'coordinator',
    recipientEmail: 'jordan.nguyen@class2class.org',
    recipientName: 'Jordan Nguyen',
    sentBy: 'partner-user-stc-director',
    sentByType: 'partner',
    customMessage: 'Join as US coordinator to lead the California district pilot.',
    token: 'c2c_invite_COORD_USA_2025',
    expiresAt: '2025-04-01T23:59:59.000Z',
    status: 'pending',
    sentAt: '2025-02-20T15:30:00.000Z',
    createdAt: '2025-02-20T15:30:00.000Z',
    updatedAt: '2025-02-28T09:00:00.000Z',
    assignedCountry: 'US',
    assignedRegion: 'California',
  },
]

const buildSeedActivities = (): PrototypeDatabase['activities'] => [
  {
    id: 'activity-2025-02-07-orestad',
    programId: 'program-climate-changemakers-2025',
    type: 'institution_joined',
    actorName: 'Ørestad Gymnasium',
    actorType: 'partner',
    description: 'Ørestad Gymnasium joined the program and activated their teacher team.',
    timestamp: '2025-02-07T10:45:00.000Z',
  },
  {
    id: 'activity-2025-02-10-nairobi',
    programId: 'program-climate-changemakers-2025',
    type: 'teacher_joined',
    actorName: 'Lekan Mutua',
    actorType: 'teacher',
    description: 'Teacher Lekan Mutua accepted the invitation and published the Tree Mappers project draft.',
    timestamp: '2025-02-10T12:45:00.000Z',
  },
  {
    id: 'activity-2025-02-24-tree-mappers',
    programId: 'program-climate-changemakers-2025',
    type: 'project_created',
    actorName: 'Astrid Larsen',
    actorType: 'teacher',
    description: 'Water Guardians project received 18 student submissions this week.',
    timestamp: '2025-02-24T18:05:00.000Z',
  },
]

const buildSeedDatabase = (): PrototypeDatabase => {
  const seededAt = new Date().toISOString()

  return {
    partners: buildSeedPartners(),
    partnerUsers: buildSeedPartnerUsers(),
    programs: buildSeedPrograms(),
    programPartners: buildSeedProgramPartners(),
    coordinators: buildSeedCoordinators(),
    institutions: buildSeedInstitutions(),
    institutionTeachers: buildSeedTeachers(),
    programProjects: buildSeedProjects(),
    invitations: buildSeedInvitations(),
    activities: buildSeedActivities(),
    metadata: {
      version: PROTOTYPE_SEED_VERSION,
      seededAt,
    },
  }
}

interface SeedOptions {
  force?: boolean
}

export const seedPrototypeDb = (options: SeedOptions = {}): {
  seeded: boolean
  reason?: 'already-seeded'
  database: PrototypeDatabase
} => {
  const current = loadPrototypeDb()

  if (!options.force) {
    const alreadySeeded = Boolean(current.metadata.seededAt) || current.programs.length > 0

    if (alreadySeeded) {
      return {
        seeded: false,
        reason: 'already-seeded',
        database: current,
      }
    }
  }

  const seededDb = buildSeedDatabase()
  persistPrototypeDb(seededDb)

  return {
    seeded: true,
    database: seededDb,
  }
}

export const getPrototypeSeedSnapshot = (): PrototypeDatabase => buildSeedDatabase()

export { PROTOTYPE_SEED_VERSION }
